name: Tests (against typescript@5.0.4)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node:
          - 18
          - 20

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (Node v${{ matrix.node }})

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install typescript@5.0.4 @types/node@18
      - run: npm run lint --workspaces --if-present
      - run: npm run build --workspace packages/knip
      - run: npx knip
      # - run: npx knip --production --strict
      - run: npm test --workspaces --if-present
